### ISSUE TITLE
Ajude-nos a escolher uma mascote

### ISSUE THREAD

**Issue by felipenmoura** [braziljs/mascote#1]
# mascote

Chegou a hora de elegermos um mascote para a BrazilJS e sua comunidade \o/
Yay!

E claro, a opinião da comunidade é **fundamental** nessa decisão tão importante ^^

Algumas premissas:

- Precisa ser brasileira(o)
- Deve lembrar "esperteza" e ao mesmo tempo, alguém que se possa confiar, simpática(o)
- Cores amarelo, preto e branco são as ideais
- Deve ficar bem em pelúcia
- Tenha traços bem reconhecíveis (para uso em vetores, adesivos, etc)
- Deve lembrar força, ser rápida(o) e ser bem vista(o) pelo público

Utilizaremos as reações nos comentários abaixo para tomar essa decisão junto dos nossos designers.  

Então, deixe uma sugestão nova, ou um comentário sobre as sugestões atuais...ou vote nas opções.

**Comment by felipenmoura** [comment]
# Onça Pintada:

![onça pintada](https://www.greenme.com.br/images/informar-se/animais/onca-pintada.jpg)

**Comment by felipenmoura** [comment]
# Jaguatirica

![Jaguatirica](https://www.sosma.org.br/wp-content/uploads/2014/10/jaguatirica-358x325.jpg)

**Comment by felipenmoura** [comment]
# Mico Leão Dourado

![Mico Leão Dourado](http://conexaoplaneta.com.br/wp-content/uploads/2017/08/mico-leao-dourado-conexao-planeta.jpg.pagespeed.ce.Txi0A9_UFT.jpg)

**Comment by felipenmoura** [comment]
# Bem-te-vi

![Bem-te-vi](https://t1.uc.ltmcdn.com/pt/images/8/2/3/img_como_cuidar_de_filhote_de_bem_te_vi_21328_600.jpg)

**Comment by nikolasFreitas** [comment]
Papagaio! Ainda dá pra ensinar a falar!

**Comment by klarkc** [comment]
# Ararajuba
![Ararajuba](https://c1.staticflickr.com/4/3115/2653596553_1eab83215a_b.jpg)

**Comment by klarkc** [comment]
# Carcará

![Carcará](https://casadospassaros.net/wp-content/uploads/2016/12/Gavi%C3%A3o-Carcar%C3%A1.jpg)

**Comment by theuves** [comment]
# Tucano

![](http://animais.culturamix.com/blog/wp-content/gallery/tucano-toco-2/Tucano-Toco-4.jpg)

**Prós**:

- É bem brasileiro, tanto que o nome *tucano* (*toucan* em inglês) [tem origem no Tupi](https://en.wikipedia.org/wiki/Toucan#Taxonomy_and_systematics) - que de acordo com [Policarpo Quaresma](https://pt.wikipedia.org/wiki/Triste_Fim_de_Policarpo_Quaresma) é o verdadeiro idioma do povo brasileiro.
- Bicho esperto, simpático, engraçado e confiável (a menos que você tenha um pomar).
- Amarelo (alaranjado), preto e branco.
- Tem traços bem reconhecíveis.

**Contras**:

- Não sei se lembra força ou velocidade.
- Alguém com a mente poluída pode comparar o seu bico com outras coisas (pior ainda se for de pelúcia).
- Pode ser associado ao [PSDB](https://pt.wikipedia.org/wiki/Partido_da_Social_Democracia_Brasileira) - nada contra às opiniões políticas, mas nunca se sabe.

**Comment by theuves** [comment]
Em relação à onça-pintada e a jaguatirica, eu creio os gringos sempre vão associar as suas imagens a um leopardo (se já é difícil distingui-los em foto, quem dirá em vetor).

Mas ainda assim acho bacana.

**Comment by welksonramos** [comment]
# Albatroz de sombranselha
![albatroz de sombranselha](https://user-images.githubusercontent.com/5823027/52634859-7050aa80-2eaf-11e9-948c-0c1de2a87e8a.jpg)

**Comment by welksonramos** [comment]
# Ema 
![ema](https://user-images.githubusercontent.com/5823027/52634898-8f4f3c80-2eaf-11e9-95a9-f5b98022b022.jpg)

**Comment by welksonramos** [comment]
# Harpia / Gavião Real
![harpia](https://user-images.githubusercontent.com/5823027/52635002-d76e5f00-2eaf-11e9-90b0-dcf345f37ca1.jpg)

**Comment by welksonramos** [comment]
# Lobo Guará
![lobo-guara](https://user-images.githubusercontent.com/5823027/52635184-5c597880-2eb0-11e9-9d4e-759045f79e54.jpg)

**Comment by welksonramos** [comment]
# Seriema
![seriema](https://user-images.githubusercontent.com/5823027/52635224-75622980-2eb0-11e9-86fa-6fbac2685d2d.jpg)

**Comment by welksonramos** [comment]
# Soldadinho do Araripe
![soldadinho do araripe](https://user-images.githubusercontent.com/5823027/52635249-8874f980-2eb0-11e9-8047-9dda28b1d263.jpg)

**Comment by welksonramos** [comment]
# Tamanduá-bandeira
![tamandua-bandeira](https://user-images.githubusercontent.com/5823027/52635265-988cd900-2eb0-11e9-8716-7d5635625405.jpg)

**Comment by narukaioh** [comment]
minha gente tem q ser amarelo preto e branco. plmd eaieahieua Tamanduá nao é amarelo XDDDD

**Comment by alinebastos** [comment]
### GATA

- Esperta e simpática
- Cores amarelo, preto e branco
- Fica ótima em pelúcia
- Tem traços bem reconhecíveis
- Lembra força, é rápida e é bem vista pelo público

![gato](https://user-images.githubusercontent.com/387470/52637179-b0b32700-2eb5-11e9-89c4-fda1ddb86cdc.jpg)

**Comment by narukaioh** [comment]
> ### GATA
> ![gato](https://user-images.githubusercontent.com/387470/52637179-b0b32700-2eb5-11e9-89c4-fda1ddb86cdc.jpg)

Aline mulé o JSLadies ja tem uma gata, tu pare kkkkkkkk

**Comment by bloodf** [comment]
# Papagaio da cabeça Amarela

![image](https://user-images.githubusercontent.com/1626923/52637656-ff14f580-2eb6-11e9-894a-a7222b288c6b.png)


O papagaio-de-cabeça-amarela possui o nome científico de Amazona oratrix. Ele pertence a família Psittacidae e em inglês é chamado de Double Yellow-Headed Amazon, Yellow-Headed Amazon ou Yellow-Headed Parrot. Ele tem como origem as Américas do Sul e Central. São aves bem grandes, medindo cerca de 40 centímetros de comprimento do bico à ponta das penas da cauda. Se bem cuidados sua expectativa de vida gira em torno de 60 ou mais anos.

Cores 100% brasileiras, super esperto e o melhor, aprende qualquer linguagem.

**Comment by tcelestino** [comment]
# Capivara

![karen-lau-653963-unsplash](https://user-images.githubusercontent.com/190265/52637969-f244d180-2eb7-11e9-8a2c-a36ccab2ff9e.jpg)
_Photo by Karen Lau on Unsplash_

O simbolo mais atual do nosso Brasil em qualquer lugar do mundo.

**Comment by AndrezaDeza** [comment]
COELHO
Veloz, sagaz, bonito e tem em tudo que é lugar :)
![rabbits_closeup_black_458774](https://user-images.githubusercontent.com/47524496/52637760-56b36100-2eb7-11e9-848c-d5f22a67a99d.jpg)

**Comment by jaydson** [comment]
# Jabuti

Jabuti ou jaboti (do tupi iawotí) é a designação vulgar, utilizada no Brasil, para duas espécies de répteis providos de carapaça, exclusivamente terrestres, nativos da América do Sul[3], do gênero Chelonoidis, da ordem dos quelônios, da família dos testudinídeos. As duas espécies de jabuti distribuídas no Brasil são a Chelonoidis carbonaria (jabuti-piranga, o mais comum) e a Chelonoidis denticulata (jabuti-tinga). A fêmea dos jabutis é chamada jabota.
Fonte: [https://pt.wikipedia.org/wiki/Jabuti](https://pt.wikipedia.org/wiki/Jabuti)

![Jabuti](https://upload.wikimedia.org/wikipedia/commons/0/08/Red_Footed_Tortoise_2.jpg)

- Simpaticão da galera
- Animal muito forte por conta de sua carapaça!
- Vive por muito tempo! Sua expectativa de vida é de até 100 anos!
- Tem tons de amarelo e preto
- "A carapaça do jabuti é preta e possui um padrão em polígonos" Polígonos são legais!

**Comment by glaucia86** [comment]
Eu particularmente, de todos os animais citados aqui, gostei mais do Bem-te-vi. Quem nunca acordou aqui com o famoso canto do bem-te-vi. 
Sem contar que é um pássaro muito comum na  América do Sul e com as cores que vocês estão precisando: amarelo, preto e branco.

Acho que tem mais a ver! 

cc: @felipenmoura

**Comment by klarkc** [comment]
Curti o bem-te-vi tbm, mas acho que o JS de hoje combina mais com o Carcará, mais sério, mais robusto, mais sólido. Levou mais porrada da vida, e sabe melhor como se virar. (talvez o lobo guará represente isso melhor)

**Comment by brunooomelo** [comment]
# Boca-preta sertanejo
* Um catchorro de origem nordestina
* Chamado "Sabichão", mais simpático que um catchorro desse, só dois "Sabichões".

![pic2b tmp](https://user-images.githubusercontent.com/12174318/52653536-44491f80-2ed7-11e9-9d27-f6e3231b0b22.jpg)

**Comment by tofanelli** [comment]
Já dá pra fazer pelúcia
não é rápido, mas transmite paz e calma
super de boas
não treta com ninguém e principalmente, agrada todo mundo

![image](https://user-images.githubusercontent.com/5512922/52666217-cc89ed80-2ef4-11e9-8293-6b172c17442b.png)

**Comment by leandrocrs** [comment]
> Bem-te-vi

É enxuto, veloz, consegue se enfiar em qualquer lugar, é bonito, a paleta de cores é praticamente a mesma do logo JS, fácil de vetorizar, vai ser facilmente associado a frontend (pode lembrar o logo do Bower), e é tão brasileiro quanto o copo americano cheio até a metade de cachaça.

A seleção é canarinho, brazilJS é bem-te-vi.

**Comment by erandirjunior** [comment]
Desculpem a brincadeira, mas não resisti:
![download](https://user-images.githubusercontent.com/13579247/52710681-b6207800-2f6e-11e9-9e55-99eb48951f1f.png)

**Comment by lemissel** [comment]
![image](https://user-images.githubusercontent.com/1514755/52734480-7b3d3500-2fac-11e9-97cd-1084eb0da22d.png)

 Dizem por aí que porcos são inteligentes, apesar de eu achar que o cachorro também ajudaria...

**Comment by jaydson** [comment]
# Bugio

![Bugio](https://upload.wikimedia.org/wikipedia/commons/b/b0/Alouatta_fusca_clamitans.jpg)

**Comment by essejose** [comment]
#  Tatu-bola
![image](https://user-images.githubusercontent.com/3483831/52789704-bf334700-304b-11e9-81a5-bf9a5f2f3121.png)

O tatu-bola, também conhecido como tatu-apara, bola, bolinha, tranquinha ou tatu-bola-do-nordeste. 
( esqueçam o fuleco  haha )

**Comment by silvoneymachado** [comment]
![image](https://user-images.githubusercontent.com/36662134/52790206-21407c00-304d-11e9-832d-3396b61cd0b3.png)

Abelha.

**Comment by theuves** [comment]
# Tapirus (a.k.a. Anta)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Brazillian_Tapir_%288679983573%29.jpg/1280px-Brazillian_Tapir_%288679983573%29.jpg)

Já que o PHP tem o elefante e o JavaScript tem/teve (ou deveria ter) algo como o rinoceronte, apresento-vos o tapirus (conhecido também como Anta).

- É bem brasileiro. O nome tapirus (em inglês *tapir*) vem do Tupi também.
- É o maior mamífero terrestre brasileiro.
- É parente dos **rinocerontes** (e dos cavalos). Veja: [Perissodáctilos](https://pt.wikipedia.org/wiki/Perissod%C3%A1ctilos).
- Tem traços reconhecíveis.
- Certamente fica bem em pelúcia.

> **Obs.:** Não tem a cor amarela, mas não existe nada que não possa ser colorido (particularmente nunca vi um elefante azul).

**Comment by cleiton-a-b** [comment]
**Boto**

![botocorderosa](https://user-images.githubusercontent.com/20826113/52790425-aaf04980-304d-11e9-89b6-ff85331dfb90.jpg)

**Comment by gm-santos** [comment]
Blanka

Rapido
![Gif do Blanka girando rapido](https://thumbs.gfycat.com/MammothThankfulBlackwidowspider-small.gif)

Esperto
![Gif do Blanka ligando um liquidificador com o próprio choque](https://thumbs.gfycat.com/KaleidoscopicTediousAlaskanhusky-small.gif)

Poderoso
![Gif do Blanka eletrocutando inimigo](https://www.blogs.unicamp.br/ciencianerd/wp-content/uploads/sites/113/2017/04/tumblr_o3yi2i4NOp1r7sijxo1_500.gif)

Carismático
![Gif do Blanka dando partida no carro para o Ken e o Ryu](https://media.giphy.com/media/Pc9xskDYldqec/giphy.gif)

**Comment by thi747** [comment]
# João-de-Barro

Nunca quebrou um build...
![flickr_-_dario_sanches_-_joao-de-barro_ furnarius_rufus _ 19](https://user-images.githubusercontent.com/2992801/52792849-7da69a00-3053-11e9-8c33-f0160ba3a426.jpg)

**Comment by Gleider** [comment]
[https://4.bp.blogspot.com/-3hzH0AFnO5Y/Wbygck_oOVI/AAAAAAAAARk/Ysd578GgOBox7mf9F7EkH8zpCknUeVrPwCLcBGAs/s1600/javali.jpg](url)

O JavaPorco, o nome já é sugestivo, além disso, encontrei uma descrição que parece interessante: "De hábito noturno, o javaporco só anda em bando e causa muito prejuízo por onde passa. Em poucos minutos tudo fica destruído..." hahaha. Ele só não é muito simpático =]

**Comment by Gleider** [comment]
### JavaPorco
![javali](https://user-images.githubusercontent.com/6404087/52793565-273a5b00-3055-11e9-8cec-fcf71b754565.jpg)

O JavaPorco, o nome já é sugestivo, além disso, encontrei uma descrição que parece interessante: "De hábito noturno, o javaporco só anda em bando e causa muito prejuízo por onde passa. Em poucos minutos tudo fica destruído..." hahaha. Ele só não é muito simpático =]

**Comment by ehauzman** [comment]
### Bicho-preguiça
Uma simpatia de animal...

![375px-bradypus](https://user-images.githubusercontent.com/6754229/52796386-dcbbdd00-305a-11e9-946c-89b64ba64e32.jpg)

**Comment by eduardoafontana** [comment]
Que tal a abelha? Poderia-se usar uma espécie brasileira, quem sabe uma que esteja em extinção, para homenagear. Além de cumprir os requisitos acima, a abelha ainda tem a característica de trabalhar bem em grupo, que representa a comunidade open source.
Ref: [Abelhas brasileiras](https://www.mundoecologia.com.br/animais/especies-de-abelhas-brasileiras/)

Abelha Jataí (Tetragonisca angustula)
Eu particularmente gostei dessa. Tem características bem definidas e deve ser de fácil vetorização. 
Além de possuir um corpo longilíneo que se diferencia dos comuns logotipos de abelas tradicionais.
Esta abelha também é conhecida como mosquitinha-verdadeira, que incomoda igual aquela funçãozinha JS que fica lá no cantinho. =P

![image](https://user-images.githubusercontent.com/6172732/52797299-bb5bf080-305c-11e9-8ddf-0e9b4abc5b6f.png)

**Comment by joaoassef** [comment]
O tucunaré é um peixe esportivo, competitivo, rápido e dinâmico entre os peixes. O Js também é muito competitivo, rápido e dinâmico.
![Tucunaré](http://1.bp.blogspot.com/-kquTOkkAa8g/Uu4eoXCsIhI/AAAAAAAABDE/Vl2vaprwMSM/s1600/21.jpeg)

**Comment by guiaparicio** [comment]
> O tucunaré é um peixe esportivo, competitivo, rápido e dinâmico entre os peixes. O Js também é muito competitivo, rápido e dinâmico.
> ![Tucunaré](https://camo.githubusercontent.com/63354731a8d2fdde0155d6988a3662e54a5da0b8/687474703a2f2f312e62702e626c6f6773706f742e636f6d2f2d6b7175544f6b6b416138672f557534656f5843734968492f41414141414141414244452f566c3276617072774d534d2f73313630302f32312e6a706567)

top!

**Comment by HDias** [comment]
![download](https://user-images.githubusercontent.com/5833611/52798766-5b168000-3057-11e9-82c2-6c7a7ce14eb5.jpeg)

O lobo-guará é uma espécie de canídeo endêmico da América do Sul e único integrante do gênero Chrysocyon. Provavelmente, a espécie vivente mais próxima é o cachorro-vinagre. Ocorre em savanas e áreas abertas no centro do Brasil, Paraguai, Argentina e Bolívia, sendo um animal típico do Cerrado. Wikipédia
Nome científico: Chrysocyon brachyurus
Comprimento: 1,2 m (Adulto) Enciclopédia da Vida
Peso: 22 kg (Adulto) Enciclopédia da Vida
Período de Gestação: 63 dias Enciclopédia da Vida
Estado de Conservação: Quase ameaçada Enciclopédia da Vida
Classificação superior: Chrysocyon

**Comment by jaydson** [comment]
Oi @HDias, o Lobo-guará já foi indicado lá em cima, e tá com muitos votos já! ehehe
Chegou a ver? https://github.com/braziljs/mascote/issues/1#issuecomment-462739766

**Comment by CristopherYusuke** [comment]
![image](https://user-images.githubusercontent.com/4607332/52800289-5790f200-3073-11e9-8af5-abaa90fdbebd.png)

![image](https://user-images.githubusercontent.com/4607332/52800361-8313dc80-3073-11e9-9e19-db527bb1b461.png)

**Comment by theuves** [comment]
Pensando um pouco mais sobre o *tamanduá-bandeira* (citado anteriormente):

- Pode ficar interessante de amarelo com a listra preta (lembrando o logo do JavaScript).
- É bem brasileiro, forte e ao mesmo tempo fofo.
- ...E o mais bacana: ele se alimenta exclusivamente de insetos (*bugs*).

![anteater-thumb](https://user-images.githubusercontent.com/10136242/52800881-784d4d80-305b-11e9-9820-b9b0c090acb1.png)
<sub>(**Obs.**: Sou péssimo *designer*... só pintei um [desenho pronto da internet](https://www.wedrawanimals.com/how-to-draw-an-anteater/).)</sub>

**Comment by diogomoretti** [comment]
# 🦜  Arara.js

Primeiro pq é Brasileira, amarela e o principal de tudo: Dá pra fazer muito bem um mascote para ficar nos eventos (penso que essa seja a ideia principal) 😜

Segundo porque em vetor também fica ótimo, dá pra usar só a cabeça ou o corpo inteiro ;)

## Exemplos
<img src="https://www.mundodosanimais.pt/wp-media/imagens/arara-caninde-ara-ararauna-1.jpg" width="350" />
<img src="https://c1.staticflickr.com/4/3115/2653596553_1eab83215a_b.jpg" width="350" />
<img src="http://meioambiente.culturamix.com/blog/wp-content/gallery/arara-de-barriga-amarela/arara-de-barriga-amarela-15.jpg" width="350" />

## Vetores
<img src="https://thumb1.shutterstock.com/photos/display_pic_with_logo/761863/118719064.jpg" width="350" />
<img src="https://cdn5.vectorstock.com/i/1000x1000/16/94/parrot-macaw-vector-4691694.jpg" width="350" />

## Fantasia
<img src="https://www.costume-shop.com/images/products/t0152.jpg" width="350" />
<img src="https://www.costume-shop.com/images/products/t0149.jpg" width="350" />

_Minha opinião é bem parecida com a do @klarkc o/_

**Comment by youngkaneda** [comment]
<img src="https://66.media.tumblr.com/383115be54499d38e74c54d866d91012/tumblr_over9quBon1vuzd7xo1_400.png"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;" />

**Comment by HDias** [comment]
> Oi @HDias, o Lobo-guará já foi indicado lá em cima, e tá com muitos votos já! ehehe
> Chegou a ver? [#1 (comment)](https://github.com/braziljs/mascote/issues/1#issuecomment-462739766)

Sinto muito, não tinha visto. Vou remover

**Comment by vagnerlandio** [comment]
# Xexéu

![xexeu](https://s3.amazonaws.com/media.wikiaves.com.br/images/1142/2411773_2620c897326bfbc961ce83ec09c935b0.jpg)

### Prós
- Cores marcantes (preto e amarelo)
- Bem esperto considerando que ele pode imitar outros pássaros como os tucanos e os papagaios. Prefere frequentar grandes grupos (como nos eventos :D) e as vezes saqueia ninho de outros pássaros (como os projetos em Node.js :D).

### Contras
- Não é exclusivo do Brasil (pode ser encontrado também em outros países da América do Central e do Sul)

**Comment by cassmtnr** [comment]
O Bem-te-vi é perfeito demais pro cargo, mas isso eu pensava até ver esse Xexéu, nem sabia da existência dessa ave, ela encaixa perfeitamente!

**Comment by artusrocha** [comment]
Galo-da-serra  (Rupicola rupicola) https://pt.wikipedia.org/wiki/Rupicola_rupicola
![14128710_1821786124709573_473836862_n](https://user-images.githubusercontent.com/1489016/52965816-7a2d4e80-3384-11e9-93fe-5c9dd6196ce3.jpg)
![galo](https://user-images.githubusercontent.com/1489016/52965821-7bf71200-3384-11e9-856a-76f79889105b.jpg)

**Comment by vlribeiro** [comment]
Além de tudo de bom que já escreveram, o **bem-te-v**i já vem com um branding sonoro fortíssimo, pra usar em podcasts ou eventos...

**Comment by youngkaneda** [comment]
![image](https://user-images.githubusercontent.com/17750608/53414693-0e636b00-39ae-11e9-81e4-71bae5794e5e.png)

O Zé Carioca

**Comment by jaydson** [comment]
Fechando a issue aqui pessoal.
Uma nova foi criada para a nova fase: https://github.com/braziljs/mascote/issues/4
Muito obrigado!

**Comment by GustavoAdolfo** [comment]
Esqueceram do símbolo nacional oficial: sabiá laranjeira
